#!/bin/bash

wget https://github.com/spinicist/riesling/releases/download/v0.1/riesling-linux.tar.gz
tar xzvf riesling-linux.tar.gz
pwd
ls -al
mkdir -p .local/bin
mv riesling .local/bin
ls -al .local/bin
echo $PATH
